### ISSUE TITLE
PHP Error $attribute

### ISSUE THREAD

**Issue by mameaw14** [gpedro/CodeIgniter-Assets-Helper#6]
to avoid error please fix
==>
in assets_helper.php
in function _assets_base($file, $attr ,$type)
from
`else
    {
      if(!empty($attr) && is_array($attr))
      {
        $attribute = ' ';
        foreach($attr as $key => $value)
        {
          $attribute .= ' '.$key.'="'.$value.'"';
        }
      }`

to

`else
    {
        $attribute = ' ';
      if(!empty($attr) && is_array($attr))
      {
        foreach($attr as $key => $value)
        {
          $attribute .= ' '.$key.'="'.$value.'"';
        }
      }`

**Comment by gpedro** [comment]
thanks you, bro. @mameaw14
