### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by AndreAmo** [gpedro/CodeIgniter-Assets-Helper#7]
I'm not sure if this was intended but in the Usage section, more specifically under the _One file with optional custom attributes_ paragraph in all the three examples the closing brackets and the semicolons are missing.

`assets_css('example.css', array('media' => 'screen')`
should be
`assets_css('example.css', array('media' => 'screen'));`

and so on. Same issue but only with the semicolons in the section above.

**Comment by gpedro** [comment]
thank you!
if you want to improve the documentation,  I will like to see a pull-request made by you

**Comment by AndreAmo** [comment]
Thank you, I'd really love to! I'll make a pull-request in the next following days then
